# Generated by Django 5.1 on 2025-10-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(blank=True, help_text='Nombre completo o apodo del usuario', max_length=150, null=True)),
                ('edad', models.IntegerField(blank=True, help_text='Edad del usuario', null=True)),
                ('email_contacto', models.EmailField(blank=True, help_text='Dirección de correo electrónico de contacto', max_length=254, null=True)),
            ],
        ),
    ]
